- hosts: jenkins
  vars:
    - jenkins_hostname: jenkins.kter.jp
    - jenkins_package_state: present
    - java_packages: openjdk-8-jdk
    - jenkins_plugins:
      - slack
    - mailserver_smtpd_banner: $myhostname ESMTP yudeazuki
    - mailserver_domain: kter.jp
    - mailserver_hostname: mail.kter.jp
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: geerlingguy.ruby
    - role: geerlingguy.git
    - role: geerlingguy.certbot
    - role: mailserver
      tags: mailserver
      become: true
  tasks:
    - name: pcapのライブラリをインストール
      apt:
        name: libpcap-dev
        state: present
