- hosts: jenkins
  vars:
    - jenkins_hostname: jenkins.kter.jp
    - jenkins_package_state: present
    - java_packages: openjdk-8-jdk
    - jenkins_plugins:
      - slack
    - mailserver_smtpd_banner: $myhostname ESMTP yudeazuki
    - mailserver_domain: kter.jp
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: geerlingguy.ruby
    - role: geerlingguy.git
    - role: geerlingguy.certbot
    - role: mailserver
      tags: mailserver
      aliases:
        - { user: root, alias: me }
        - { user: kter, alias: tomohico.takahashi@gmail.com }
        - { user: me, alias: tomohico.takahashi@gmail.com }
        - { user: aws2, alias: me }
        - { user: aws3, alias: me }
        - { user: aws4, alias: me }
        - { user: aws5, alias: me }
        - { user: shinkansen, alias: me }
      become: true
  tasks:
    - name: pcapのライブラリをインストール
      apt:
        name: libpcap-dev
        state: present
