---
#- name: Firewalldサービスの再起動
#  service:
#    name: firewalld
#    state: restarted
- name: Postfixサービスの再起動
  service:
    name: postfix
    state: restarted
- name: Dovecotサービスの再起動
  service:
    name: dovecot
    state: restarted
- name: aliases再構築
  command: newaliases
  notify: Postfixサービスの再起動

