---
- name: メールサーバに必要なサーバをインストール
  apt:
    name: "{{ item }}"
  with_items:
    - postfix
    - dovecot-core
    - dovecot-imapd
- name: メールサーバ起動と自動起動の有効化
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - postfix
    - dovecot

